# Generated by Django 3.2 on 2022-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_tokenproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenProxy',
        ),
    ]
