# Generated by Django 3.2 on 2022-10-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribtions',
        ),
    ]
