# Generated by Django 3.2 on 2022-10-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytokenproxy',
            name='token_ptr',
        ),
        migrations.DeleteModel(
            name='MyToken',
        ),
        migrations.DeleteModel(
            name='MyTokenProxy',
        ),
    ]
